export * from './icon'
export * from './drawer'
export * from './avatar'
export * from './tree'
export * from './pagination'
export * from './button'
export * from './calendar'
export * from './checkbox'
export * from './dropdown'
export * from './form'
export * from './input'
export * from './menu'
export * from './modal'
export * from './popover'
export * from './progress'
export * from './switch'
export * from './upload'
export * from './virtual-list'
// import BAvatar from '@bear-ui/components/avatar'
// import BIcon from '@bear-ui/components/icon'
// import BTree from '@bear-ui/components/tree'
// import BCheckBox from '@bear-ui/components/checkbox'
// import BPagination from '@bear-ui/components/pagination'
// import '@bear-ui/theme-chalk/src/index.scss'
// const plugins = [BAvatar, BIcon, BTree, BCheckBox, BPagination]

// export default plugins
