"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const index = require("./icon/index.js");
const index$1 = require("./drawer/index.js");
const index$2 = require("./avatar/index.js");
const index$3 = require("./tree/index.js");
const index$5 = require("./pagination/index.js");
const index$4 = require("./checkbox/index.js");
require("./packages/theme-chalk/src/index.scss.js");
const icon = require("./icon/src/icon.js");
const drawer = require("./drawer/src/drawer.js");
const avatar = require("./avatar/src/avatar.js");
const tree = require("./tree/src/tree.js");
const pagination = require("./pagination/src/pagination.js");
const plugins = [index$2.BAvatar, index.BIcon, index$3.BTree, index$4.default, index$5.default];
exports.BIcon = index.BIcon;
exports.Drawer = index$1.Drawer;
exports.BAvatar = index$2.BAvatar;
exports.BTree = index$3.BTree;
exports.iconProps = icon.iconProps;
exports.drawerProps = drawer.drawerProps;
exports.avatarEmits = avatar.avatarEmits;
exports.avatarProps = avatar.avatarProps;
exports.treeEmitts = tree.treeEmitts;
exports.treeInjectKey = tree.treeInjectKey;
exports.treeNodeContentProps = tree.treeNodeContentProps;
exports.treeNodeEmitts = tree.treeNodeEmitts;
exports.treeNodeProps = tree.treeNodeProps;
exports.treeProps = tree.treeProps;
exports.paginationProps = pagination.paginationProps;
exports.default = plugins;
//# sourceMappingURL=index.js.map
