name: Bear-UI Pnpm

on:
  push:
    # master 分支有 push 时触发
    branches: [master]

jobs:
  deploy:
    # 指定虚拟机环境
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build Docs
        run: pnpm docs:build
      # - name: Serve Docs
      #   run: pnpm docs:serve
